export interface Task {
  id?: number; // Optional since it may be generated by IndexedDB
  name: string;
  createdAt?: string;
  executedAt?: string;
  url: string;
  method?: string;
  headers?: Record<string, string>;
  body?: any;
  status?: "pending" | "complete" | "failed";
  result?: any;
  error?: string;
}

export interface ExtendableMessageData {
  action: "enqueue";
  task: Task;
}

export interface ExtendableMessageEvent extends MessageEvent {
  data: ExtendableMessageData;
}

export interface TaskUpdateMessageData {
  type: "TASK_UPDATE";
  task: Task;
}
